sudo: required

language: bash

services:
  - docker

env:
  - IMAGE='php:7.1-cli' TNT_CLIENT=pecl
  - IMAGE='php:7.1-cli'
  - IMAGE='php:7.2-cli' PHPUNIT_OPTS='--coverage-clover=coverage.clover'
  - IMAGE='php:7.3-rc-cli'

install:
  - ./dockerfile.sh | tee /dev/tty | docker build -t queue -

script:
  - docker network create tarantool-php
  - docker run -d --net=tarantool-php --name=tarantool -v `pwd`:/queue tarantool/tarantool:1 tarantool /queue/tests/Integration/queues.lua
  - docker run --rm --net=tarantool-php -v `pwd`:/queue -w /queue -e PHPUNIT_OPTS="$PHPUNIT_OPTS" queue

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      docker run --rm -v $(pwd):/coverage -w /coverage queue php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
