sudo: required

language: bash

services:
  - docker

env:
  - IMAGE='php:5.6-cli' TNT_CLIENT=pecl
  - IMAGE='php:7.0-cli' TNT_CLIENT=pecl
  - IMAGE='php:7.1-cli' TNT_CLIENT=pecl
  - IMAGE='php:5.6-cli' TNT_CLIENT=pure
  - IMAGE='php:7.0-cli' TNT_CLIENT=pure
  - IMAGE='php:7.1-cli' TNT_CLIENT=pure
  - IMAGE='php:7.2-cli' TNT_CLIENT=pure PHPUNIT_OPTS='--coverage-clover=coverage.clover'

install:
  - ./dockerfile.sh | tee /dev/tty | docker build -t queue -

script:
  - docker network create tarantool-php
  - docker run -d --net=tarantool-php --name=tarantool -v `pwd`:/queue tarantool/tarantool:1.7 tarantool /queue/tests/Integration/queues.lua
  - docker run --rm --net=tarantool-php --name=queue -v `pwd`:/queue -w /queue -e PHPUNIT_OPTS="$PHPUNIT_OPTS" queue

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
