sudo: required

language: bash

services:
  - docker

env:
  - PHP_RUNTIME='php:5.4-cli'
  - PHP_RUNTIME='php:5.5-cli'
  - PHP_RUNTIME='php:5.6-cli' PHPUNIT_OPTS='--coverage-clover=coverage.clover'

install:
  - ./dockerfile.sh | docker build -t queue -

script:
  - docker run -d --name tarantool -v $(pwd):/queue tarantool/tarantool /queue/tests/Integration/queues.lua
  - docker run --rm --name queue --link tarantool -v $(pwd):/queue -w /queue -e PHPUNIT_OPTS="$PHPUNIT_OPTS" queue

after_script:
  - docker run --rm --name queue -v $(pwd):/queue -w /queue queue bash -c "
      if [[ -f coverage.clover ]]; then
        curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
      fi
    "
